name: Up requirement

on:
  push:
    branches: [master, dev]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Set up python 3.11
        uses: actions/setup-python@v4
        with:
            python-version: '3.11'

      - name: Install toml-to-requirements
        run: |
          pip install toml-to-requirements

      - name: Export requirements.txt
        run: |
          toml-to-req --toml-file pyproject.toml

      - name: Upload requirements.txt
        uses: EndBug/add-and-commit@v9.1.3
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: ':wrench: 自动更新requirements'
          add: |
            'requirements.txt'
